openapi: 3.1.0
info:
  title: audits.v1
paths:
  /audits.v1.AuditsService/GetInventoryTransactionAuditLogs:
    post:
      tags:
        - audits.v1.AuditsService
      summary: GetInventoryTransactionAuditLogs
      operationId: audits.v1.AuditsService.GetInventoryTransactionAuditLogs
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/audits.v1.GetInventoryTransactionAuditLogsRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/audits.v1.GetInventoryTransactionAuditLogsResponse'
  /audits.v1.AuditsService/GetVoucherTransactionAuditLogs:
    post:
      tags:
        - audits.v1.AuditsService
      summary: GetVoucherTransactionAuditLogs
      operationId: audits.v1.AuditsService.GetVoucherTransactionAuditLogs
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/audits.v1.GetVoucherTransactionAuditLogsRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/audits.v1.GetVoucherTransactionAuditLogsResponse'
components:
  schemas:
    audits.v1.GetInventoryTransactionAuditLogsRequest:
      type: object
      properties:
        storeId:
          type: string
          title: store_id
      title: GetInventoryTransactionAuditLogsRequest
      required:
        - storeId
      additionalProperties: false
    audits.v1.GetInventoryTransactionAuditLogsResponse:
      type: object
      properties:
        inventoryTransactions:
          type: array
          items:
            $ref: '#/components/schemas/audits.v1.InventoryTransaction'
          title: inventory_transactions
      title: GetInventoryTransactionAuditLogsResponse
      additionalProperties: false
    audits.v1.GetVoucherTransactionAuditLogsRequest:
      type: object
      properties:
        storeId:
          type: string
          title: store_id
      title: GetVoucherTransactionAuditLogsRequest
      required:
        - storeId
      additionalProperties: false
    audits.v1.GetVoucherTransactionAuditLogsResponse:
      type: object
      properties:
        voucherTransactions:
          type: array
          items:
            $ref: '#/components/schemas/audits.v1.VoucherTransaction'
          title: voucher_transactions
      title: GetVoucherTransactionAuditLogsResponse
      additionalProperties: false
    audits.v1.InventoryTransaction:
      type: object
      properties:
        documentId:
          type: string
          title: document_id
          description: '"TXN-2025-00123"'
          nullable: true
        storeId:
          type: string
          title: store_id
        productId:
          type: string
          title: product_id
        transactionType:
          title: transaction_type
          $ref: '#/components/schemas/audits.v1.TransactionType'
        quantityChange:
          type: integer
          title: quantity_change
          format: int32
          description: Positive = increase, negative = decrease
        quantityBefore:
          type: integer
          title: quantity_before
          format: int32
          description: Stock level before
        quantityAfter:
          type: integer
          title: quantity_after
          format: int32
          description: Stock level after
        relatedDocumentType:
          type: string
          title: related_document_type
          description: '"DeliveryNote", "ReceivingNote", etc.'
        relatedDocumentId:
          type: string
          title: related_document_id
          description: ID of the document
        performedByUserId:
          type: string
          title: performed_by_user_id
        transactionTime:
          title: transaction_time
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        notes:
          type: string
          title: notes
        batchId:
          type: string
          title: batch_id
          description: Specific batch affected
      title: InventoryTransaction
      required:
        - documentId
      additionalProperties: false
      description: |-
        *
         InventoryTransaction (Journal des Mouvements)
         Complete audit trail of every inventory change.
         Auto-generated by all operations that affect stock.

         Fix: Added batch_id for lot-specific transactions.

         Example:
           transaction_id: "TXN-2025-00123"
           warehouse_id: "WH-001"
           product_id: "PRD-001"
           transaction_type: TXN_TYPE_SALE
           quantity_change: -10
           quantity_before: 100
           quantity_after: 90
           related_document_type: "DeliveryNote"
           related_document_id: "DN-2025-001"
           performed_by_user_id: "USR-003"
           batch_id: "BATCH-2025-001"
    audits.v1.TransactionType:
      type: string
      title: TransactionType
      enum:
        - TXN_TYPE_UNSPECIFIED
        - TXN_TYPE_PURCHASE
        - TXN_TYPE_SALE
        - TXN_TYPE_RETURN_IN
        - TXN_TYPE_RETURN_OUT
        - TXN_TYPE_TRANSFER_OUT
        - TXN_TYPE_TRANSFER_IN
        - TXN_TYPE_ADJUSTMENT
        - TXN_TYPE_DAMAGE
        - TXN_TYPE_THEFT
        - TXN_TYPE_INITIAL
        - TXN_TYPE_EXPIRATION
    audits.v1.VoucherTransaction:
      type: object
      properties:
        documentId:
          type: string
          title: document_id
        voucherId:
          type: string
          title: voucher_id
          description: Which voucher used
        relatedInvoiceId:
          type: string
          title: related_invoice_id
          description: Which purchase
        relatedReceiptId:
          type: string
          title: related_receipt_id
          description: Or cash receipt
        amountUsed:
          type: number
          title: amount_used
          format: double
        remainingAfter:
          type: number
          title: remaining_after
          format: double
        usedAt:
          title: used_at
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        usedByUserId:
          type: string
          title: used_by_user_id
      title: VoucherTransaction
      required:
        - documentId
      additionalProperties: false
      description: |-
        *
         VoucherTransaction tracks each time a voucher is used.

         Example:
           transaction_id: "VT-001"
           voucher_id: "GV-2025-001"
           related_invoice_id: "INV-2025-005"
           amount_used: 50000
           remaining_after: 50000
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/connect.error_details.Any'
          description: A list of messages that carry the error details. There is no limit on the number of messages.
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    connect.error_details.Any:
      type: object
      properties:
        type:
          type: string
          description: 'A URL that acts as a globally unique identifier for the type of the serialized message. For example: `type.googleapis.com/google.rpc.ErrorInfo`. This is used to determine the schema of the data in the `value` field and is the discriminator for the `debug` field.'
        value:
          type: string
          format: binary
          description: The Protobuf message, serialized as bytes and base64-encoded. The specific message type is identified by the `type` field.
        debug:
          oneOf:
            - type: object
              title: Any
              additionalProperties: true
              description: Detailed error information.
          discriminator:
            propertyName: type
          title: Debug
          description: Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message, with an additional debug field for ConnectRPC error details.
    google.protobuf.Timestamp:
      type: string
      examples:
        - "2023-01-15T01:30:15.01Z"
        - "2024-12-25T12:00:00Z"
      format: date-time
      description: |-
        A Timestamp represents a point in time independent of any time zone or local
         calendar, encoded as a count of seconds and fractions of seconds at
         nanosecond resolution. The count is relative to an epoch at UTC midnight on
         January 1, 1970, in the proleptic Gregorian calendar which extends the
         Gregorian calendar backwards to year one.

         All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
         second table is needed for interpretation, using a [24-hour linear
         smear](https://developers.google.com/time/smear).

         The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
         restricting to that range, we ensure that we can convert to and from [RFC
         3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

         # Examples

         Example 1: Compute Timestamp from POSIX `time()`.

             Timestamp timestamp;
             timestamp.set_seconds(time(NULL));
             timestamp.set_nanos(0);

         Example 2: Compute Timestamp from POSIX `gettimeofday()`.

             struct timeval tv;
             gettimeofday(&tv, NULL);

             Timestamp timestamp;
             timestamp.set_seconds(tv.tv_sec);
             timestamp.set_nanos(tv.tv_usec * 1000);

         Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

             FILETIME ft;
             GetSystemTimeAsFileTime(&ft);
             UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

             // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
             // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
             Timestamp timestamp;
             timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
             timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

         Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

             long millis = System.currentTimeMillis();

             Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
                 .setNanos((int) ((millis % 1000) * 1000000)).build();

         Example 5: Compute Timestamp from Java `Instant.now()`.

             Instant now = Instant.now();

             Timestamp timestamp =
                 Timestamp.newBuilder().setSeconds(now.getEpochSecond())
                     .setNanos(now.getNano()).build();

         Example 6: Compute Timestamp from current time in Python.

             timestamp = Timestamp()
             timestamp.GetCurrentTime()

         # JSON Mapping

         In JSON format, the Timestamp type is encoded as a string in the
         [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
         format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
         where {year} is always expressed using four digits while {month}, {day},
         {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
         seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
         are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
         is required. A proto3 JSON serializer should always use UTC (as indicated by
         "Z") when printing the Timestamp type and a proto3 JSON parser should be
         able to accept both UTC and other timezones (as indicated by an offset).

         For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
         01:30 UTC on January 15, 2017.

         In JavaScript, one can convert a Date object to this format using the
         standard
         [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
         method. In Python, a standard `datetime.datetime` object can be converted
         to this format using
         [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
         the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
         the Joda Time's [`ISODateTimeFormat.dateTime()`](
         http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
         ) to obtain a formatter capable of generating timestamps in this format.
security: []
tags:
  - name: audits.v1.AuditsService
