openapi: 3.1.0
info:
  title: order.v1
paths: {}
components:
  schemas:
    inventory.v1.Internationalized:
      type: object
      properties:
        en:
          type: string
          title: en
          description: The English name of the product category.
        fr:
          type: string
          title: fr
          description: The French name of the product category.
      title: Internationalized
      additionalProperties: false
    order.v1.OrderLineItem:
      type: object
      properties:
        productId:
          type: string
          title: product_id
          description: Which product
        quantity:
          type: integer
          title: quantity
          format: int32
          description: How many units
        productName:
          title: product_name
          description: Product name
          $ref: '#/components/schemas/inventory.v1.Internationalized'
        unitPrice:
          type: number
          title: unit_price
          format: double
          description: Price per unit (in smallest currency)
        total:
          type: number
          title: total
          format: double
          description: quantity * unit_price
        batchId:
          type: string
          title: batch_id
          description: 'Optional: Specific batch/lot requested'
          nullable: true
      title: OrderLineItem
      additionalProperties: false
      description: |-
        *
         OrderLineItem represents a single product line in an order or quotation.
         Used in PurchaseOrder, SalesOrder, Quotation, etc.

         Fix: Added optional batch_id for specifying lots in orders (e.g., for perishable goods).

         Example:
           product_id: "PRD-001"
           quantity: 10
           product_name: "Product Name"
           unit_price: 450000
           total: 4500000
           batch_id: "BATCH-2025-001" (optional)
security: []
