package auth

import (
	"context"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"math/rand"
	"net/http"
	"strings"
	"time"

	"connectrpc.com/connect"
	identityv1 "github.com/karibu-cap/sabitou/protos/gen/go/rpc/identity/v1"
	"github.com/sabitou/powersync/connector/internal/db"
	"github.com/sabitou/powersync/connector/internal/models"
	"golang.org/x/crypto/bcrypt"
)

// Handler handles all authentication HTTP routes.
type Handler struct {
	db         *db.DB
	jwtService *JWTService
	logger     *slog.Logger
}

// NewHandler creates a new auth Handler.
func NewHandler(database *db.DB, jwtService *JWTService, logger *slog.Logger) *Handler {
	return &Handler{
		db:         database,
		jwtService: jwtService,
		logger:     logger,
	}
}

// =========================================================================
// Login
// =========================================================================

// Login authenticates a user with email/phone/username + password and returns tokens.
func (h *Handler) Login(ctx context.Context, req *connect.Request[identityv1.LoginRequest]) (*connect.Response[identityv1.LoginResponse], error) {
	msg := req.Msg

	var emailOrPhoneOrUser string
	if msg.Email != nil {
		emailOrPhoneOrUser = *msg.Email
	} else if msg.PhoneNumber != nil {
		emailOrPhoneOrUser = *msg.PhoneNumber
	} else if msg.UserName != nil {
		emailOrPhoneOrUser = *msg.UserName
	}

	emailOrPhoneOrUser = strings.TrimSpace(strings.ToLower(emailOrPhoneOrUser))
	if emailOrPhoneOrUser == "" || msg.Password == "" {
		h.logger.Error("missing credentials", "identifier", emailOrPhoneOrUser)
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.New("missing credentials"))
	}

	user, err := h.getUserByEmailOrPhoneOrUser(ctx, emailOrPhoneOrUser)
	if err != nil || user == nil {
		h.logger.Error("user not found", "error", err, "identifier", emailOrPhoneOrUser)
		// Constant-time response to prevent user enumeration.
		bcrypt.CompareHashAndPassword([]byte("$2a$12$dummy"), []byte(msg.Password)) //nolint:errcheck
		return nil, connect.NewError(connect.CodeUnauthenticated, errors.New("invalid credentials"))
	}

	passwordHash, err := h.getPasswordHash(ctx, *user.RefId)
	if err != nil {
		h.logger.Error("failed to get password hash", "error", err, "ref_id", user.RefId)
		return nil, connect.NewError(connect.CodeUnauthenticated, errors.New("invalid credentials"))
	}

	if err := bcrypt.CompareHashAndPassword([]byte(passwordHash), []byte(msg.Password)); err != nil {
		h.logger.Error("password mismatch", "error", err, "ref_id", user.RefId)
		return nil, connect.NewError(connect.CodeUnauthenticated, errors.New("invalid credentials"))
	}

	accessToken, refreshToken, err := h.buildAuthTokens(ctx, user)
	if err != nil {
		h.logger.Error("build auth tokens failed", "error", err)
		return nil, connect.NewError(connect.CodeInternal, errors.New("authentication failed"))
	}

	resp := &identityv1.LoginResponse{
		Token:        accessToken,
		RefreshToken: refreshToken,
	}
	return connect.NewResponse(resp), nil
}

// =========================================================================
// Register
// =========================================================================

// Register creates a new user account via Connect RPC.
func (h *Handler) Register(ctx context.Context, req *connect.Request[identityv1.RegisterRequest]) (*connect.Response[identityv1.RegisterResponse], error) {
	msg := req.Msg

	email := strings.TrimSpace(strings.ToLower(msg.Email))
	if email == "" || msg.Password == "" || msg.UserName == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.New("user_name, email and password are required"))
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(msg.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("could not hash password"))
	}

	// ref_id is auto-generated by the DB DEFAULT (gen_random_uuid()).
	// The caller may supply one in future by populating the proto field, but
	// for the standard register flow we let the server decide.
	refID := GenerateSmartUserID("USR")
	err = h.db.QueryRow(ctx, `
		INSERT INTO users (ref_id, user_name, email, password_hash)
		VALUES ($1, $2, $3, $4)
		RETURNING ref_id
	`, refID, msg.UserName, email, string(hash)).Scan(&refID)
	if err != nil {
		if strings.Contains(err.Error(), "unique") {
			return nil, connect.NewError(connect.CodeAlreadyExists, errors.New("email or username already registered"))
		}
		h.logger.Error("insert user", "error", err)
		return nil, connect.NewError(connect.CodeInternal, errors.New("registration failed"))
	}

	user, err := h.getUserByRefID(ctx, refID)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("registration succeeded but user retrieval failed"))
	}

	accessToken, refreshToken, err := h.buildAuthTokens(ctx, user)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("token generation failed"))
	}

	resp := &identityv1.RegisterResponse{
		Token:        accessToken,
		RefreshToken: refreshToken,
	}
	return connect.NewResponse(resp), nil
}

// RequestPasswordReset implements the reset stub
func (h *Handler) RequestPasswordReset(ctx context.Context, req *connect.Request[identityv1.RequestPasswordResetRequest]) (*connect.Response[identityv1.RequestPasswordResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("not implemented"))
}

// ResetPassword implements the reset stub
func (h *Handler) ResetPassword(ctx context.Context, req *connect.Request[identityv1.ResetPasswordRequest]) (*connect.Response[identityv1.ResetPasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("not implemented"))
}

// =========================================================================
// Refresh
// =========================================================================

// RefreshToken issues a new access + refresh token pair, rotating the refresh token.
func (h *Handler) RefreshToken(ctx context.Context, req *connect.Request[identityv1.RefreshTokenRequest]) (*connect.Response[identityv1.RefreshTokenResponse], error) {
	msg := req.Msg

	if msg.RefreshToken == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.New("refresh_token is required"))
	}

	tokenHash := hashToken(msg.RefreshToken)

	var userID string
	err := h.db.QueryRow(ctx, `
		SELECT user_id FROM refresh_tokens
		WHERE token_hash = $1 AND revoked = FALSE AND expires_at > NOW()
	`, tokenHash).Scan(&userID)
	if err != nil {
		return nil, connect.NewError(connect.CodeUnauthenticated, errors.New("refresh token is invalid or expired"))
	}

	// Revoke used token (rotation prevents replay attacks).
	if _, err := h.db.Exec(ctx, `
		UPDATE refresh_tokens SET revoked = TRUE WHERE token_hash = $1
	`, tokenHash); err != nil {
		h.logger.Error("revoke refresh token", "error", err)
	}

	user, err := h.getUserByRefID(ctx, userID)
	if err != nil || user == nil {
		return nil, connect.NewError(connect.CodeUnauthenticated, errors.New("user not found"))
	}

	accessToken, refreshToken, err := h.buildAuthTokens(ctx, user)
	if err != nil {
		h.logger.Error("build auth response", "error", err)
		return nil, connect.NewError(connect.CodeInternal, errors.New("token generation failed"))
	}

	resp := &identityv1.RefreshTokenResponse{
		Token:        accessToken,
		RefreshToken: refreshToken,
	}
	return connect.NewResponse(resp), nil
}

// =========================================================================
// Logout
// =========================================================================

// Logout revokes all refresh tokens for the authenticated user.
// DELETE /api/v1/auth/logout
// Requires Authorization: Bearer <access_token>
func (h *Handler) Logout(w http.ResponseWriter, r *http.Request) {
	claims, ok := ClaimsFromContext(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "UNAUTHORIZED", "missing authentication")
		return
	}

	if _, err := h.db.Exec(r.Context(), `
		UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1 AND revoked = FALSE
	`, claims.UserID); err != nil {
		h.logger.Error("logout revoke tokens", "error", err, "user_id", claims.UserID)
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "logout failed")
		return
	}

	w.WriteHeader(http.StatusNoContent)
}

// =========================================================================
// Helpers
// =========================================================================

// buildAuthTokens issues a JWT access token and a rotating refresh token for
// the given user.
func (h *Handler) buildAuthTokens(ctx context.Context, user *identityv1.User) (string, string, error) {
	accessToken, _, err := h.jwtService.IssueAccessToken(*user.RefId)
	if err != nil {
		return "", "", fmt.Errorf("issue access token: %w", err)
	}

	rawRefresh, refreshHash := generateRefreshToken()

	_, err = h.db.Exec(ctx, `
		INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
		VALUES ($1, $2, $3)
	`, user.RefId, refreshHash, time.Now().Add(h.jwtService.RefreshTokenTTL()))
	if err != nil {
		return "", "", fmt.Errorf("store refresh token: %w", err)
	}

	return accessToken, rawRefresh, nil
}

func (h *Handler) getUserByEmailOrPhoneOrUser(ctx context.Context, identifier string) (*identityv1.User, error) {
	row := h.db.QueryRow(ctx, `
		SELECT ref_id, user_name, COALESCE(email, ''), COALESCE(first_name, ''), COALESCE(last_name, ''),
		       COALESCE(phone_number, ''), account_status, created_at
		FROM users WHERE (email = $1 OR phone_number = $1 OR user_name = $1) AND account_status != 'ACCOUNT_STATUS_TYPE_DELETED'
	`, identifier)
	return scanUser(row)
}

func (h *Handler) getUserByRefID(ctx context.Context, refID string) (*identityv1.User, error) {
	row := h.db.QueryRow(ctx, `
		SELECT ref_id, user_name, COALESCE(email, ''), COALESCE(first_name, ''), COALESCE(last_name, ''),
		       COALESCE(phone_number, ''), account_status, created_at
		FROM users WHERE ref_id = $1
	`, refID)
	return scanUser(row)
}

func (h *Handler) getPasswordHash(ctx context.Context, refID string) (string, error) {
	var hash string
	err := h.db.QueryRow(ctx, `SELECT password_hash FROM users WHERE ref_id = $1`, refID).Scan(&hash)
	return hash, err
}

// scanUser reads a user row into a models.User.
// The query must SELECT the columns in the exact order used here.
func scanUser(row interface{ Scan(...any) error }) (*identityv1.User, error) {
	u := &identityv1.User{}
	err := row.Scan(
		&u.RefId, &u.UserName, &u.Email,
		&u.FirstName, &u.LastName, &u.PhoneNumber,
		&u.AccountStatus, &u.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return u, nil
}

// generateRefreshToken returns (rawToken, sha256Hash).
// We store only the hash in the database.
func generateRefreshToken() (string, string) {
	b := make([]byte, 40)
	cryptorand.Read(b) //nolint:errcheck
	raw := base64.RawURLEncoding.EncodeToString(b)
	return raw, hashToken(raw)
}

// GenerateSmartUserID génère un ID type USER-2026-1703-001
func GenerateSmartUserID(db_key string) string {
	now := time.Now()
	year := now.Year()
	dayMonth := fmt.Sprintf("%02d%02d", now.Day(), int(now.Month()))
	randomNumber := rand.Intn(1000)
	return fmt.Sprintf("%s-%d-%s-%03d", db_key, year, dayMonth, randomNumber)
}

func hashToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// =========================================================================
// HTTP helpers
// =========================================================================

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v) //nolint:errcheck
}

func writeError(w http.ResponseWriter, status int, code, message string) {
	writeJSON(w, status, models.ErrorResponse{Code: code, Message: message})
}
