name: sabitou_clients
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.8.1"
  flutter: ">=3.32.5"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Package to print a debug log.
  logger: ^2.4.0

  # synchronous key-value in memory.
  get_storage: ^2.1.1

  sabitou_rpc:
    path: ../protos/gen/dart
    
  # Hive Community Edition - A spiritual continuation of Hive v2
  hive_ce: ^2.10.1

  # Hive Community Edition - A spiritual continuation of Hive v2
  hive_ce_flutter: ^2.2.0

  # Auto size text
  auto_size_text: ^3.0.0

  # Shadcn UI
  shadcn_ui: ^0.27.4

  # Clock package to handle time.
  clock: ^1.1.2

  # Collection of widgets animations.
  animation_wrappers: ^3.0.0

  # Package of internationalization.
  intl: ^0.20.2

  # Package to show a loading animation.
  flutter_spinkit: ^5.2.2

  # Package to connect to the gRPC server.
  connectrpc: ^1.0.0

  # Package to inject dependencies.
  get_it: ^8.2.0

  # Package to manage the state of the application.
  provider: ^6.1.5+1

  # Package to scan barcode.
  mobile_scanner: ^7.0.1

  # Package to manage the state of the application.
  rxdart: ^0.28.0

  # Package to show a loading animation.
  shimmer_animation: ^2.2.2

  #Flutter Package that provides methods for fetching currencies information, All information about conversion currency are updated once a day.
  geo_currencies: ^0.0.6

  # Package to pick an image from the device.
  image_picker: ^1.2.0

  # Syncfusion Flutter Charts
  syncfusion_flutter_charts: ^28.2.12

  #Isar database has a powerful query language that allows you to make use of your indexes.
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2

  # Package to generate a unique id.
  uuid: ^4.4.2

  # Package to manage the navigation between screens.
  go_router: ^16.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # APIs and utilities for UI testing via screenshots diffing.
  golden_toolkit: ^0.15.0

  # Package for mocking, stubing, faking in tests.
  mockito: ^5.4.4

  # Provides a concrete way of generating files using Dart code, outside of tools like pub.
  # Since Mockito uses a generated file of the mocked class we will need to generate this file
  # for every mocked class. Visit https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md
  # on how to generate the new library.
  build_runner: ^2.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_ce_generator: ^1.8.1

  # Dart code linter.
  dart_code_linter: any

  # The isar community generator.
  isar_community_generator: ^3.3.0-dev.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # Default font used across the Place apps.
    # Link to poppins font: https://fonts.google.com/specimen/Poppins.
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700
