FROM golang:1.24.0-alpine

RUN apk add git ca-certificates
RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /build

# Copie le module local référencé par le replace directive
COPY protos/gen/go ./protos/gen/go

# Copie les fichiers de dépendances du connector
WORKDIR /build/powersync/connector
COPY powersync/connector/go.mod powersync/connector/go.sum ./
RUN go mod download

WORKDIR /build/powersync/connector
ENTRYPOINT ["air", "-c", ".air.toml"]