// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: order/order.proto

package order

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// OrderService Interface
// ======================

type OrderService interface {
	// Creates a new order.
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)

	// Gets an order by id.
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)

	// Deletes an order.
	DeleteOrder(context.Context, *DeleteOrderRequest) (*DeleteOrderResponse, error)
}

// ============================
// OrderService Protobuf Client
// ============================

type orderServiceProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewOrderServiceProtobufClient creates a Protobuf client that implements the OrderService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewOrderServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) OrderService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "karibu.sabitou.order", "OrderService")
	urls := [3]string{
		serviceURL + "CreateOrder",
		serviceURL + "GetOrder",
		serviceURL + "DeleteOrder",
	}

	return &orderServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *orderServiceProtobufClient) CreateOrder(ctx context.Context, in *CreateOrderRequest) (*CreateOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateOrder")
	caller := c.callCreateOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateOrderRequest) when calling interceptor")
					}
					return c.callCreateOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceProtobufClient) callCreateOrder(ctx context.Context, in *CreateOrderRequest) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *orderServiceProtobufClient) GetOrder(ctx context.Context, in *GetOrderRequest) (*GetOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "GetOrder")
	caller := c.callGetOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetOrderRequest) when calling interceptor")
					}
					return c.callGetOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceProtobufClient) callGetOrder(ctx context.Context, in *GetOrderRequest) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *orderServiceProtobufClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteOrder")
	caller := c.callDeleteOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteOrderRequest) when calling interceptor")
					}
					return c.callDeleteOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceProtobufClient) callDeleteOrder(ctx context.Context, in *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	out := new(DeleteOrderResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// OrderService JSON Client
// ========================

type orderServiceJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewOrderServiceJSONClient creates a JSON client that implements the OrderService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewOrderServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) OrderService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "karibu.sabitou.order", "OrderService")
	urls := [3]string{
		serviceURL + "CreateOrder",
		serviceURL + "GetOrder",
		serviceURL + "DeleteOrder",
	}

	return &orderServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *orderServiceJSONClient) CreateOrder(ctx context.Context, in *CreateOrderRequest) (*CreateOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateOrder")
	caller := c.callCreateOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateOrderRequest) when calling interceptor")
					}
					return c.callCreateOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceJSONClient) callCreateOrder(ctx context.Context, in *CreateOrderRequest) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *orderServiceJSONClient) GetOrder(ctx context.Context, in *GetOrderRequest) (*GetOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "GetOrder")
	caller := c.callGetOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetOrderRequest) when calling interceptor")
					}
					return c.callGetOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceJSONClient) callGetOrder(ctx context.Context, in *GetOrderRequest) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *orderServiceJSONClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteOrder")
	caller := c.callDeleteOrder
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteOrderRequest) when calling interceptor")
					}
					return c.callDeleteOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *orderServiceJSONClient) callDeleteOrder(ctx context.Context, in *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	out := new(DeleteOrderResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// OrderService Server Handler
// ===========================

type orderServiceServer struct {
	OrderService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewOrderServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewOrderServiceServer(svc OrderService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &orderServiceServer{
		OrderService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *orderServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *orderServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// OrderServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const OrderServicePathPrefix = "/twirp/karibu.sabitou.order.OrderService/"

func (s *orderServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.order")
	ctx = ctxsetters.WithServiceName(ctx, "OrderService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "karibu.sabitou.order.OrderService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateOrder":
		s.serveCreateOrder(ctx, resp, req)
		return
	case "GetOrder":
		s.serveGetOrder(ctx, resp, req)
		return
	case "DeleteOrder":
		s.serveDeleteOrder(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *orderServiceServer) serveCreateOrder(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateOrderJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateOrderProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *orderServiceServer) serveCreateOrderJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateOrderRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.OrderService.CreateOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateOrderRequest) when calling interceptor")
					}
					return s.OrderService.CreateOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateOrderResponse and nil error while calling CreateOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) serveCreateOrderProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateOrderRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.OrderService.CreateOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateOrderRequest) when calling interceptor")
					}
					return s.OrderService.CreateOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreateOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreateOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreateOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateOrderResponse and nil error while calling CreateOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) serveGetOrder(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetOrderJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetOrderProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *orderServiceServer) serveGetOrderJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetOrderRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.OrderService.GetOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetOrderRequest) when calling interceptor")
					}
					return s.OrderService.GetOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetOrderResponse and nil error while calling GetOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) serveGetOrderProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetOrderRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.OrderService.GetOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetOrderRequest) when calling interceptor")
					}
					return s.OrderService.GetOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetOrderResponse and nil error while calling GetOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) serveDeleteOrder(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteOrderJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteOrderProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *orderServiceServer) serveDeleteOrderJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteOrderRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.OrderService.DeleteOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteOrderRequest) when calling interceptor")
					}
					return s.OrderService.DeleteOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteOrderResponse and nil error while calling DeleteOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) serveDeleteOrderProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteOrder")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteOrderRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.OrderService.DeleteOrder
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteOrderRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteOrderRequest) when calling interceptor")
					}
					return s.OrderService.DeleteOrder(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteOrderResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteOrderResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteOrderResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteOrderResponse and nil error while calling DeleteOrder. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *orderServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *orderServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *orderServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "karibu.sabitou.order", "OrderService")
}

var twirpFileDescriptor1 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xda, 0x4a,
	0x10, 0xc6, 0x10, 0x08, 0x8c, 0x09, 0xc7, 0xd9, 0xe4, 0x1c, 0x71, 0xd2, 0x44, 0xa1, 0x4e, 0x9b,
	0xd2, 0x48, 0x25, 0x2a, 0xed, 0x03, 0x94, 0xc0, 0x36, 0x45, 0xa2, 0xc6, 0x5a, 0x9b, 0x8b, 0xb6,
	0x17, 0x96, 0xb1, 0xf7, 0xc2, 0x6a, 0xb0, 0x1d, 0xef, 0xba, 0x11, 0x6f, 0xd0, 0x07, 0xe8, 0x33,
	0xf4, 0x15, 0xfa, 0x7a, 0x95, 0xd7, 0x36, 0xe1, 0x2f, 0xfd, 0xb9, 0x41, 0xbb, 0xdf, 0x7c, 0x7c,
	0x33, 0xdf, 0xcc, 0x78, 0x61, 0x3f, 0x88, 0x5c, 0x1a, 0x5d, 0x8a, 0xdf, 0x4e, 0x18, 0x05, 0x3c,
	0x40, 0x87, 0x9f, 0xed, 0xc8, 0x9b, 0xc6, 0x1d, 0x66, 0x4f, 0x3d, 0x1e, 0xc4, 0x1d, 0x11, 0x53,
	0xef, 0xa0, 0x36, 0x4e, 0x0e, 0x43, 0x4e, 0x67, 0xe8, 0x14, 0xe4, 0x30, 0x0a, 0xdc, 0xd8, 0xe1,
	0x56, 0xec, 0xb9, 0x4d, 0xa9, 0x25, 0xb5, 0x6b, 0x04, 0x32, 0x68, 0xe2, 0xb9, 0xe8, 0x08, 0xaa,
	0xb7, 0xb1, 0xed, 0x73, 0x8f, 0xcf, 0x9b, 0xc5, 0x96, 0xd4, 0x2e, 0x93, 0xc5, 0x1d, 0xbd, 0x80,
	0x83, 0xd8, 0xf7, 0xb8, 0x15, 0x46, 0x9e, 0x43, 0x2d, 0xcf, 0xb7, 0x1c, 0xea, 0x73, 0xd6, 0x2c,
	0x09, 0x9a, 0x92, 0x84, 0xf4, 0x24, 0x32, 0xf4, 0xfb, 0x09, 0xae, 0x7e, 0x2b, 0x41, 0x59, 0x64,
	0x46, 0x0a, 0x94, 0xee, 0xb3, 0x25, 0x47, 0x74, 0x06, 0x7b, 0x11, 0x65, 0x41, 0x1c, 0x39, 0xd4,
	0xe2, 0xf3, 0x90, 0x8a, 0x5c, 0x35, 0x52, 0xcf, 0x41, 0x73, 0x1e, 0x52, 0xf4, 0x18, 0x16, 0x77,
	0x51, 0x6d, 0x49, 0x70, 0xe4, 0x1c, 0x4b, 0xca, 0x7d, 0x03, 0xb2, 0x70, 0x69, 0x79, 0x9c, 0xce,
	0x58, 0x73, 0xa7, 0x55, 0x6a, 0xcb, 0xdd, 0xd3, 0xce, 0xb6, 0x46, 0x74, 0x16, 0x5d, 0x20, 0x10,
	0xe4, 0x47, 0x86, 0x2e, 0xe1, 0x90, 0x07, 0xdc, 0xbe, 0x59, 0x77, 0x55, 0x16, 0xae, 0xf6, 0x45,
	0x6c, 0xd9, 0x16, 0x7a, 0x0d, 0x15, 0xc6, 0x6d, 0x1e, 0xb3, 0x66, 0xa5, 0x25, 0xb5, 0x1b, 0xdd,
	0xe3, 0xed, 0xd9, 0x0c, 0xc1, 0x21, 0x19, 0x17, 0x9d, 0x00, 0x38, 0x11, 0xb5, 0x39, 0x75, 0x2d,
	0x9b, 0x37, 0x77, 0x85, 0x93, 0x5a, 0x86, 0xf4, 0x38, 0x7a, 0x02, 0x8d, 0x3c, 0x3c, 0x9d, 0x0b,
	0xb3, 0xd5, 0xb4, 0x21, 0x19, 0x7a, 0x35, 0x4f, 0xdc, 0x9e, 0x00, 0xc4, 0xa1, 0x9b, 0x8b, 0xd4,
	0x52, 0x91, 0x0c, 0x49, 0x45, 0xf2, 0x70, 0x26, 0x02, 0xa9, 0x48, 0x86, 0x0a, 0x11, 0xf5, 0xbb,
	0x04, 0xa8, 0x2f, 0x54, 0x45, 0x43, 0x08, 0xbd, 0x8d, 0x29, 0xe3, 0xe8, 0x25, 0x94, 0x45, 0xe1,
	0x62, 0x4a, 0x72, 0xf7, 0xd1, 0x2f, 0x7a, 0x48, 0x52, 0x26, 0x6a, 0xc3, 0x1e, 0x8b, 0xc3, 0xf0,
	0xc6, 0xa3, 0x91, 0xe5, 0xdb, 0xb3, 0x6c, 0x88, 0xef, 0x0a, 0xa4, 0x9e, 0xc3, 0x9a, 0x3d, 0xa3,
	0x5f, 0x25, 0x29, 0x99, 0xe4, 0x34, 0x66, 0x9e, 0x4f, 0x19, 0x5b, 0x9e, 0x64, 0x8e, 0x4d, 0x3c,
	0xf7, 0x4a, 0x81, 0x86, 0xb5, 0xa2, 0xa6, 0x3e, 0x83, 0x83, 0x95, 0x3a, 0x59, 0x18, 0xf8, 0x8c,
	0x6e, 0x2e, 0x93, 0x7a, 0x06, 0xff, 0x5c, 0x53, 0xbe, 0xe2, 0x66, 0x93, 0x84, 0x41, 0xb9, 0x27,
	0x65, 0x52, 0x7f, 0xef, 0x59, 0x3d, 0x07, 0x34, 0xa0, 0x37, 0x74, 0xad, 0x79, 0x9b, 0xe9, 0x2e,
	0xe1, 0x60, 0x85, 0x97, 0x65, 0x6c, 0xc2, 0x2e, 0x8b, 0x1d, 0x87, 0x32, 0x26, 0xc8, 0x55, 0x92,
	0x5f, 0x2f, 0xee, 0xa0, 0x92, 0xae, 0x0c, 0xfa, 0x0f, 0x90, 0x61, 0xf6, 0xcc, 0x89, 0x61, 0x4d,
	0x34, 0x43, 0xc7, 0xfd, 0xe1, 0xdb, 0x21, 0x1e, 0x28, 0x05, 0x84, 0xa0, 0x91, 0xe1, 0x3a, 0xd6,
	0x06, 0x43, 0xed, 0x5a, 0x91, 0xd0, 0xbf, 0xb0, 0x9f, 0x63, 0x64, 0xdc, 0xc7, 0x86, 0x91, 0xc0,
	0x45, 0x74, 0x08, 0x4a, 0x06, 0xf7, 0xc7, 0xef, 0xf5, 0x11, 0x36, 0xf1, 0x40, 0x29, 0x2d, 0xa3,
	0x3d, 0xad, 0x8f, 0x47, 0x23, 0x3c, 0x50, 0x76, 0x2e, 0x6e, 0xa1, 0x4e, 0x96, 0xbf, 0xba, 0x13,
	0xf8, 0x9f, 0x60, 0x63, 0x3c, 0x21, 0x7d, 0x6c, 0x99, 0x1f, 0x74, 0xbc, 0x56, 0x45, 0x0b, 0x8e,
	0x57, 0xc3, 0x43, 0xcd, 0xc4, 0x44, 0xeb, 0x8d, 0x2c, 0xc3, 0x1c, 0x13, 0xac, 0x48, 0x9b, 0x0c,
	0x63, 0xa2, 0xeb, 0xa3, 0x21, 0x26, 0x19, 0xa3, 0xd8, 0xfd, 0x51, 0x84, 0xba, 0xe8, 0x8b, 0x41,
	0xa3, 0x2f, 0x9e, 0x43, 0x91, 0x0b, 0xf2, 0xd2, 0xa8, 0x51, 0x7b, 0xfb, 0x20, 0x36, 0xb7, 0xf6,
	0xe8, 0xf9, 0x1f, 0x30, 0xd3, 0xd6, 0xab, 0x05, 0xf4, 0x09, 0xaa, 0xf9, 0x0a, 0xa0, 0xa7, 0xdb,
	0xff, 0xb8, 0xb6, 0x47, 0x47, 0xe7, 0xbf, 0xa3, 0x2d, 0xc4, 0x5d, 0x90, 0x97, 0x06, 0xfe, 0x90,
	0x85, 0xcd, 0xdd, 0x79, 0xc8, 0xc2, 0x96, 0xed, 0x51, 0x0b, 0x57, 0xf2, 0xc7, 0x5a, 0x14, 0x3a,
	0xe9, 0xab, 0x3f, 0xad, 0x88, 0x67, 0xff, 0xd5, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xe1,
	0xae, 0x91, 0x0b, 0x06, 0x00, 0x00,
}
