// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: identity/user.proto

package identity

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =====================
// UserService Interface
// =====================

type UserService interface {
	// Get the user information for the currently authenticated user.
	GetMe(context.Context, *Empty) (*User, error)

	// Get the public information for the given user id.
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)

	// Update the user information for the currently authenticated user.
	UpdateMe(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)

	// Request the deletion of the user account.
	// This will send a verification code to the user's email address
	// or phone number.
	RequestDeleteUser(context.Context, *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error)

	// Processes the deletion of the user account requested by the user.
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)

	// Change the password for the currently authenticated user.
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
}

// ===========================
// UserService Protobuf Client
// ===========================

type userServiceProtobufClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserServiceProtobufClient creates a Protobuf client that implements the UserService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewUserServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "karibu.sabitou.identity", "UserService")
	urls := [6]string{
		serviceURL + "GetMe",
		serviceURL + "GetUser",
		serviceURL + "UpdateMe",
		serviceURL + "RequestDeleteUser",
		serviceURL + "DeleteUser",
		serviceURL + "ChangePassword",
	}

	return &userServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userServiceProtobufClient) GetMe(ctx context.Context, in *Empty) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetMe")
	caller := c.callGetMe
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Empty) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Empty)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Empty) when calling interceptor")
					}
					return c.callGetMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callGetMe(ctx context.Context, in *Empty) (*User, error) {
	out := new(User)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) GetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	caller := c.callGetUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetUserRequest) when calling interceptor")
					}
					return c.callGetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callGetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) UpdateMe(ctx context.Context, in *UpdateUserRequest) (*UpdateUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateMe")
	caller := c.callUpdateMe
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return c.callUpdateMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callUpdateMe(ctx context.Context, in *UpdateUserRequest) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) RequestDeleteUser(ctx context.Context, in *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "RequestDeleteUser")
	caller := c.callRequestDeleteUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RequestDeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RequestDeleteUserRequest) when calling interceptor")
					}
					return c.callRequestDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RequestDeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RequestDeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callRequestDeleteUser(ctx context.Context, in *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
	out := new(RequestDeleteUserResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) DeleteUser(ctx context.Context, in *DeleteUserRequest) (*DeleteUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteUser")
	caller := c.callDeleteUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteUserRequest) when calling interceptor")
					}
					return c.callDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callDeleteUser(ctx context.Context, in *DeleteUserRequest) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ChangePassword")
	caller := c.callChangePassword
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ChangePasswordRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ChangePasswordRequest) when calling interceptor")
					}
					return c.callChangePassword(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ChangePasswordResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ChangePasswordResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callChangePassword(ctx context.Context, in *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// UserService JSON Client
// =======================

type userServiceJSONClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserServiceJSONClient creates a JSON client that implements the UserService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewUserServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "karibu.sabitou.identity", "UserService")
	urls := [6]string{
		serviceURL + "GetMe",
		serviceURL + "GetUser",
		serviceURL + "UpdateMe",
		serviceURL + "RequestDeleteUser",
		serviceURL + "DeleteUser",
		serviceURL + "ChangePassword",
	}

	return &userServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userServiceJSONClient) GetMe(ctx context.Context, in *Empty) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetMe")
	caller := c.callGetMe
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *Empty) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Empty)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Empty) when calling interceptor")
					}
					return c.callGetMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callGetMe(ctx context.Context, in *Empty) (*User, error) {
	out := new(User)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) GetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	caller := c.callGetUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetUserRequest) when calling interceptor")
					}
					return c.callGetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callGetUser(ctx context.Context, in *GetUserRequest) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) UpdateMe(ctx context.Context, in *UpdateUserRequest) (*UpdateUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateMe")
	caller := c.callUpdateMe
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return c.callUpdateMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callUpdateMe(ctx context.Context, in *UpdateUserRequest) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) RequestDeleteUser(ctx context.Context, in *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "RequestDeleteUser")
	caller := c.callRequestDeleteUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RequestDeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RequestDeleteUserRequest) when calling interceptor")
					}
					return c.callRequestDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RequestDeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RequestDeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callRequestDeleteUser(ctx context.Context, in *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
	out := new(RequestDeleteUserResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) DeleteUser(ctx context.Context, in *DeleteUserRequest) (*DeleteUserResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteUser")
	caller := c.callDeleteUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteUserRequest) when calling interceptor")
					}
					return c.callDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callDeleteUser(ctx context.Context, in *DeleteUserRequest) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ChangePassword")
	caller := c.callChangePassword
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ChangePasswordRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ChangePasswordRequest) when calling interceptor")
					}
					return c.callChangePassword(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ChangePasswordResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ChangePasswordResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callChangePassword(ctx context.Context, in *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// UserService Server Handler
// ==========================

type userServiceServer struct {
	UserService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewUserServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewUserServiceServer(svc UserService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &userServiceServer{
		UserService:      svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *userServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *userServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// UserServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const UserServicePathPrefix = "/twirp/karibu.sabitou.identity.UserService/"

func (s *userServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "karibu.sabitou.identity")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "karibu.sabitou.identity.UserService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "GetMe":
		s.serveGetMe(ctx, resp, req)
		return
	case "GetUser":
		s.serveGetUser(ctx, resp, req)
		return
	case "UpdateMe":
		s.serveUpdateMe(ctx, resp, req)
		return
	case "RequestDeleteUser":
		s.serveRequestDeleteUser(ctx, resp, req)
		return
	case "DeleteUser":
		s.serveDeleteUser(ctx, resp, req)
		return
	case "ChangePassword":
		s.serveChangePassword(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *userServiceServer) serveGetMe(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetMeJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetMeProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveGetMeJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMe")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(Empty)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.GetMe
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Empty) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Empty)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Empty) when calling interceptor")
					}
					return s.UserService.GetMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling GetMe. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveGetMeProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMe")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(Empty)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.GetMe
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *Empty) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*Empty)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*Empty) when calling interceptor")
					}
					return s.UserService.GetMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling GetMe. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveGetUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveGetUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetUserRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.GetUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetUserRequest) when calling interceptor")
					}
					return s.UserService.GetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetUserResponse and nil error while calling GetUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveGetUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.GetUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetUserRequest) when calling interceptor")
					}
					return s.UserService.GetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetUserResponse and nil error while calling GetUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateMe(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateMeJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateMeProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveUpdateMeJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateMe")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateUserRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.UpdateMe
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return s.UserService.UpdateMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdateUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdateUserResponse and nil error while calling UpdateMe. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateMeProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateMe")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.UpdateMe
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return s.UserService.UpdateMe(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdateUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdateUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdateUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdateUserResponse and nil error while calling UpdateMe. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveRequestDeleteUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRequestDeleteUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRequestDeleteUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveRequestDeleteUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RequestDeleteUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(RequestDeleteUserRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.RequestDeleteUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RequestDeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RequestDeleteUserRequest) when calling interceptor")
					}
					return s.UserService.RequestDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RequestDeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RequestDeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *RequestDeleteUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RequestDeleteUserResponse and nil error while calling RequestDeleteUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveRequestDeleteUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RequestDeleteUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(RequestDeleteUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.RequestDeleteUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *RequestDeleteUserRequest) (*RequestDeleteUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*RequestDeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*RequestDeleteUserRequest) when calling interceptor")
					}
					return s.UserService.RequestDeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*RequestDeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*RequestDeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *RequestDeleteUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RequestDeleteUserResponse and nil error while calling RequestDeleteUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveDeleteUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveDeleteUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteUserRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.DeleteUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteUserRequest) when calling interceptor")
					}
					return s.UserService.DeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteUserResponse and nil error while calling DeleteUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveDeleteUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.DeleteUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteUserRequest) when calling interceptor")
					}
					return s.UserService.DeleteUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteUserResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteUserResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteUserResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteUserResponse and nil error while calling DeleteUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveChangePassword(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveChangePasswordJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveChangePasswordProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveChangePasswordJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ChangePassword")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ChangePasswordRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.ChangePassword
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ChangePasswordRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ChangePasswordRequest) when calling interceptor")
					}
					return s.UserService.ChangePassword(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ChangePasswordResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ChangePasswordResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ChangePasswordResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ChangePasswordResponse and nil error while calling ChangePassword. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveChangePasswordProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ChangePassword")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ChangePasswordRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.ChangePassword
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ChangePasswordRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ChangePasswordRequest) when calling interceptor")
					}
					return s.UserService.ChangePassword(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ChangePasswordResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ChangePasswordResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ChangePasswordResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ChangePasswordResponse and nil error while calling ChangePassword. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor2, 0
}

func (s *userServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *userServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "karibu.sabitou.identity", "UserService")
}

var twirpFileDescriptor2 = []byte{
	// 1010 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0x6f, 0x73, 0xda, 0xc6,
	0x13, 0xc7, 0x8d, 0xc1, 0x36, 0x2c, 0x18, 0x8b, 0xfb, 0xfd, 0xda, 0xca, 0x24, 0x4e, 0x88, 0xd2,
	0x3f, 0xae, 0x3d, 0x83, 0x27, 0xf4, 0x0d, 0x54, 0x80, 0x6c, 0x34, 0x63, 0x0b, 0xe6, 0x24, 0xdc,
	0x26, 0x33, 0xed, 0xcd, 0x59, 0xba, 0x04, 0x4d, 0x6c, 0x89, 0xe8, 0x4e, 0xf6, 0x78, 0xa6, 0x2f,
	0xa0, 0xcf, 0xfb, 0xbe, 0xfa, 0x42, 0xfa, 0x12, 0xfa, 0xa8, 0xa3, 0x43, 0x22, 0x60, 0x50, 0xe3,
	0xe6, 0x19, 0xb7, 0xf7, 0xb9, 0xdd, 0xef, 0xee, 0xed, 0x2d, 0x82, 0xff, 0xf9, 0x1e, 0x0b, 0x84,
	0x2f, 0xee, 0x4f, 0x62, 0xce, 0xa2, 0xf6, 0x34, 0x0a, 0x45, 0x88, 0xbe, 0x7a, 0x4f, 0x23, 0xff,
	0x2a, 0x6e, 0x73, 0x7a, 0xe5, 0x8b, 0x30, 0x6e, 0x67, 0x8c, 0x36, 0x05, 0xa5, 0x17, 0x06, 0x01,
	0x73, 0x05, 0xf3, 0x74, 0xd7, 0x0d, 0xe3, 0x40, 0x20, 0x1d, 0xca, 0xd3, 0x28, 0xbc, 0xf5, 0x3d,
	0x16, 0xa9, 0x85, 0x56, 0xe1, 0xb0, 0xde, 0xf9, 0xa6, 0x9d, 0x73, 0xbe, 0x3d, 0x4a, 0x41, 0xe7,
	0x7e, 0xca, 0xf0, 0xfc, 0x18, 0xda, 0x87, 0x72, 0x44, 0xef, 0x88, 0x47, 0x05, 0x55, 0x8b, 0xad,
	0xc2, 0x61, 0x05, 0xef, 0x44, 0xf4, 0xae, 0x4f, 0x05, 0xd5, 0xfe, 0x2a, 0x41, 0x69, 0xcc, 0x59,
	0x84, 0x14, 0x28, 0xc6, 0xbe, 0x27, 0x23, 0x54, 0x70, 0xf2, 0x13, 0x3d, 0x81, 0x4a, 0xa2, 0x99,
	0x04, 0xf4, 0x86, 0xa9, 0x9b, 0xd2, 0x5e, 0x4e, 0x0c, 0x16, 0xbd, 0x61, 0xe8, 0x67, 0x40, 0x6e,
	0xa6, 0x94, 0xd0, 0x99, 0x54, 0x2e, 0x9d, 0x57, 0x3b, 0xdf, 0xe7, 0xea, 0x7b, 0x98, 0x1c, 0x6e,
	0xb8, 0x0f, 0x2c, 0x1c, 0xed, 0xc3, 0x16, 0xbb, 0xa1, 0xfe, 0xb5, 0x5a, 0x4a, 0x42, 0x0e, 0x36,
	0xf0, 0x6c, 0xf9, 0x7b, 0xa1, 0x80, 0xbe, 0x85, 0xda, 0x74, 0x12, 0x06, 0x8c, 0x04, 0xf1, 0xcd,
	0x15, 0x8b, 0xd4, 0x2d, 0x49, 0x14, 0x70, 0x55, 0x5a, 0x2d, 0x69, 0x4c, 0x38, 0x0d, 0xe0, 0xad,
	0x1f, 0x71, 0x31, 0x93, 0xbe, 0x2d, 0xa9, 0x4d, 0x5c, 0x91, 0xb6, 0x44, 0x7d, 0xc2, 0xb4, 0xa0,
	0x72, 0x4d, 0x33, 0x64, 0x47, 0x22, 0x45, 0x5c, 0x4e, 0x4c, 0x19, 0x71, 0x08, 0xbb, 0x53, 0xca,
	0xf9, 0x5d, 0x18, 0x79, 0x64, 0x42, 0xf9, 0x44, 0x2d, 0x4b, 0xaa, 0x84, 0x6b, 0x99, 0x79, 0x40,
	0xf9, 0x24, 0x21, 0x2f, 0xa1, 0x9e, 0x96, 0x80, 0x70, 0x41, 0x45, 0xcc, 0xd5, 0x8a, 0xbc, 0xa8,
	0xa3, 0xdc, 0x42, 0xa4, 0xd9, 0xda, 0x92, 0x4e, 0x6e, 0x6b, 0xb0, 0x85, 0x77, 0xe9, 0xa2, 0x31,
	0xf1, 0x8b, 0x41, 0x89, 0xd8, 0x87, 0xd8, 0x8f, 0x64, 0x8d, 0x85, 0x1f, 0x06, 0x5c, 0x85, 0x56,
	0xf1, 0xb0, 0xde, 0xf9, 0x2e, 0xdf, 0x73, 0x2c, 0x26, 0xba, 0x64, 0x65, 0x13, 0xec, 0x65, 0x0e,
	0x66, 0x36, 0x8e, 0x0e, 0x00, 0xdc, 0x88, 0x51, 0x79, 0x6d, 0x42, 0xad, 0xc9, 0x6b, 0xad, 0xa4,
	0x16, 0x5d, 0x74, 0xcb, 0xb0, 0x4d, 0x64, 0xbd, 0xbb, 0x7b, 0xb0, 0x4b, 0x16, 0xab, 0xdd, 0xdd,
	0x85, 0x2a, 0xf9, 0x58, 0xd6, 0x6e, 0x0d, 0x80, 0xcc, 0x2b, 0xd8, 0x55, 0xa0, 0x4e, 0x96, 0xaa,
	0xd5, 0x6d, 0xc0, 0x1e, 0x59, 0xae, 0x8a, 0xa6, 0x41, 0xfd, 0x8c, 0x89, 0xa4, 0xdd, 0x30, 0xfb,
	0x10, 0x33, 0x2e, 0x56, 0xbb, 0x4e, 0xeb, 0xc3, 0xde, 0x9c, 0xe1, 0xd3, 0x30, 0xe0, 0x0c, 0xbd,
	0x82, 0x52, 0xd2, 0x77, 0x92, 0xaa, 0x76, 0x0e, 0x72, 0x53, 0x97, 0x87, 0x24, 0xaa, 0x9d, 0x42,
	0x63, 0x3c, 0xf5, 0xa8, 0x60, 0x8b, 0xc1, 0x3e, 0xc3, 0xcf, 0x19, 0xa0, 0x45, 0x3f, 0x9f, 0x2f,
	0x68, 0x00, 0x6a, 0x2a, 0xa3, 0xcf, 0xae, 0xd9, 0xb2, 0xae, 0xd5, 0xa7, 0xd7, 0x84, 0x72, 0x56,
	0xcc, 0xec, 0xe5, 0x65, 0x6b, 0xed, 0x47, 0xd8, 0x5f, 0xe3, 0x29, 0x55, 0xf6, 0x12, 0x76, 0xa3,
	0xd9, 0x26, 0x11, 0xe1, 0x7b, 0x16, 0xa4, 0x4e, 0x6b, 0xa9, 0xd1, 0x49, 0x6c, 0x1a, 0x83, 0xc6,
	0xaa, 0x88, 0xc7, 0x9c, 0x44, 0xc7, 0xd0, 0xb8, 0x65, 0x91, 0xff, 0xd6, 0x77, 0x69, 0xd2, 0x4d,
	0xc4, 0x0d, 0xbd, 0x6c, 0x34, 0x28, 0x8b, 0x1b, 0xbd, 0xd0, 0x63, 0x5a, 0x1b, 0xd0, 0x1a, 0x85,
	0x2a, 0xec, 0xf0, 0xd8, 0x75, 0x19, 0xe7, 0x32, 0x42, 0x19, 0x67, 0x4b, 0xed, 0x17, 0xf8, 0xa2,
	0x37, 0xa1, 0xc1, 0x3b, 0x36, 0x4a, 0x53, 0xcd, 0xa4, 0xbd, 0x80, 0x5a, 0x78, 0xed, 0xcd, 0xdb,
	0x2b, 0x55, 0x56, 0x0d, 0xaf, 0xbd, 0x8c, 0x4c, 0x90, 0x80, 0xdd, 0x91, 0x07, 0x45, 0xab, 0x06,
	0xec, 0x2e, 0x43, 0xb4, 0x0e, 0x7c, 0xf9, 0xd0, 0xfd, 0x27, 0x25, 0xed, 0xc0, 0x96, 0x71, 0x33,
	0x15, 0xf7, 0x47, 0xf7, 0xd0, 0x58, 0x79, 0xb2, 0xe8, 0x25, 0x3c, 0xd7, 0x7b, 0xbd, 0xe1, 0xd8,
	0x72, 0x88, 0xed, 0xe8, 0xce, 0xd8, 0x26, 0xce, 0xeb, 0x91, 0x41, 0xc6, 0x96, 0x3d, 0x32, 0x7a,
	0xe6, 0xa9, 0x69, 0xf4, 0x95, 0x0d, 0xf4, 0x0c, 0x9a, 0xeb, 0x20, 0xbd, 0xe7, 0x98, 0x97, 0x86,
	0x52, 0x40, 0xcf, 0xe1, 0xc9, 0xba, 0xfd, 0xbe, 0x71, 0x6e, 0x38, 0x46, 0x5f, 0xd9, 0x3c, 0xfa,
	0xb3, 0x00, 0xf5, 0xe5, 0x47, 0x8d, 0x5a, 0xf0, 0x54, 0x1f, 0x3b, 0x03, 0xe9, 0x64, 0x68, 0xad,
	0x8b, 0xfa, 0x02, 0x0e, 0x56, 0x88, 0x4b, 0x03, 0x9b, 0xa7, 0xaf, 0x89, 0x71, 0xa1, 0x9b, 0xe7,
	0x4a, 0x32, 0xde, 0xbe, 0xce, 0x43, 0x46, 0x83, 0xa1, 0x65, 0x10, 0x6b, 0x7c, 0xd1, 0x35, 0xb0,
	0xb2, 0xb9, 0x96, 0x34, 0x2d, 0xd3, 0x31, 0xf5, 0x73, 0xf3, 0x8d, 0x41, 0x46, 0xba, 0x6d, 0xff,
	0x34, 0xc4, 0x7d, 0xa5, 0x28, 0x2b, 0xf2, 0x90, 0xc4, 0x86, 0x6d, 0x38, 0x1f, 0xa1, 0xd2, 0xd1,
	0x1f, 0x05, 0xa8, 0x2d, 0xfe, 0x51, 0xa1, 0x03, 0xd8, 0x1f, 0xe1, 0xe1, 0xa5, 0xd9, 0x37, 0xf0,
	0xba, 0x5c, 0x5a, 0xf0, 0x74, 0x79, 0xfb, 0xd4, 0xc4, 0x46, 0x57, 0xb7, 0x8d, 0x79, 0x2a, 0x2a,
	0xfc, 0x7f, 0x99, 0x38, 0x1b, 0x0e, 0xcf, 0xce, 0x8d, 0x99, 0xf4, 0xe5, 0x1d, 0xd3, 0x72, 0x0c,
	0x6c, 0xe9, 0xe7, 0xa4, 0x3b, 0xb6, 0x4d, 0xcb, 0xb0, 0x6d, 0x92, 0x08, 0x56, 0x8a, 0x9d, 0xbf,
	0x4b, 0x50, 0x4d, 0x1a, 0xd5, 0x66, 0xd1, 0xad, 0xef, 0x32, 0x34, 0x80, 0xad, 0x33, 0x26, 0x2e,
	0x18, 0x7a, 0x96, 0xfb, 0xbc, 0x65, 0x6b, 0x34, 0xff, 0xfd, 0xf9, 0x6b, 0x1b, 0xe8, 0x57, 0xd8,
	0x49, 0x27, 0x1a, 0xca, 0x1f, 0xdb, 0xcb, 0x73, 0xb1, 0x79, 0xf8, 0x69, 0x70, 0xd6, 0xbc, 0xda,
	0x06, 0x62, 0x50, 0x9e, 0xcd, 0xa8, 0x0b, 0x86, 0xf2, 0xff, 0x71, 0x56, 0xc6, 0x61, 0xf3, 0xf8,
	0x51, 0xec, 0x3c, 0xcc, 0x6f, 0xd0, 0x58, 0x99, 0x3b, 0xe8, 0x55, 0xae, 0x8f, 0xbc, 0x69, 0xd7,
	0xec, 0xfc, 0x97, 0x23, 0xf3, 0xe8, 0xef, 0x00, 0x16, 0xc2, 0xe6, 0xa7, 0xb9, 0x1a, 0xef, 0xf8,
	0x51, 0xec, 0x3c, 0x10, 0x87, 0xfa, 0xf2, 0x98, 0x40, 0xed, 0xfc, 0xcf, 0x99, 0x75, 0xe3, 0xaa,
	0x79, 0xf2, 0x68, 0x3e, 0x0b, 0xda, 0xad, 0xbf, 0xa9, 0x45, 0x53, 0xf7, 0x24, 0x03, 0xaf, 0xb6,
	0xe5, 0x77, 0xe2, 0x0f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xf3, 0xcc, 0xc9, 0x3e, 0x0a,
	0x00, 0x00,
}
