version: "3"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest-dev # user latest-dev for local development
    entrypoint:
      - /surreal
      - start
      - --log
      - trace
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb://sabitou/sabitou.db
      - --allow-scripting
      - --allow-funcs
      - --allow-net
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - data:/sabitou/db
    restart: on-failure

volumes:
  data:
