openapi: 3.1.0
info:
  title: store.v1
paths:
  /store.v1.SupplierService/CreateSupplier:
    post:
      tags:
        - store.v1.SupplierService
      summary: Creates a new supplier.
      description: Creates a new supplier.
      operationId: store.v1.SupplierService.CreateSupplier
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/store.v1.CreateSupplierRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store.v1.CreateSupplierResponse'
  /store.v1.SupplierService/DeleteSupplier:
    post:
      tags:
        - store.v1.SupplierService
      summary: Deletes a supplier.
      description: Deletes a supplier.
      operationId: store.v1.SupplierService.DeleteSupplier
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/store.v1.DeleteSupplierRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store.v1.DeleteSupplierResponse'
  /store.v1.SupplierService/GetStoreSuppliers:
    post:
      tags:
        - store.v1.SupplierService
      summary: Gets all suppliers of a store.
      description: Gets all suppliers of a store.
      operationId: store.v1.SupplierService.GetStoreSuppliers
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/store.v1.GetStoreSuppliersRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store.v1.GetStoreSuppliersResponse'
  /store.v1.SupplierService/GetSupplier:
    post:
      tags:
        - store.v1.SupplierService
      summary: Gets a supplier by id.
      description: Gets a supplier by id.
      operationId: store.v1.SupplierService.GetSupplier
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/store.v1.GetSupplierRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store.v1.GetSupplierResponse'
  /store.v1.SupplierService/StreamStoreSuppliers: {}
  /store.v1.SupplierService/UpdateSupplier:
    post:
      tags:
        - store.v1.SupplierService
      summary: Updates a supplier.  Note:Only the fields that are set will be updated. array fields like external_links will be replaced.
      description: |-
        Updates a supplier.
         Note:Only the fields that are set will be updated. array fields like external_links will be replaced.
      operationId: store.v1.SupplierService.UpdateSupplier
      parameters:
        - name: Connect-Protocol-Version
          in: header
          required: true
          schema:
            $ref: '#/components/schemas/connect-protocol-version'
        - name: Connect-Timeout-Ms
          in: header
          schema:
            $ref: '#/components/schemas/connect-timeout-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/store.v1.UpdateSupplierRequest'
        required: true
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/connect.error'
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store.v1.UpdateSupplierResponse'
components:
  schemas:
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/connect.error_details.Any'
          description: A list of messages that carry the error details. There is no limit on the number of messages.
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    connect.error_details.Any:
      type: object
      properties:
        type:
          type: string
          description: 'A URL that acts as a globally unique identifier for the type of the serialized message. For example: `type.googleapis.com/google.rpc.ErrorInfo`. This is used to determine the schema of the data in the `value` field and is the discriminator for the `debug` field.'
        value:
          type: string
          format: binary
          description: The Protobuf message, serialized as bytes and base64-encoded. The specific message type is identified by the `type` field.
        debug:
          oneOf:
            - type: object
              title: Any
              additionalProperties: true
              description: Detailed error information.
          discriminator:
            propertyName: type
          title: Debug
          description: Deserialized error detail payload. The 'type' field indicates the schema. This field is for easier debugging and should not be relied upon for application logic.
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message, with an additional debug field for ConnectRPC error details.
    link.v1.ResourceLink:
      type: object
      properties:
        refId:
          type: string
          title: ref_id
          description: The unique identifier of the resource link.
          nullable: true
        targetUri:
          type: string
          title: target_uri
          description: The link of the resource link.
        iconUri:
          type: string
          title: icon_uri
          description: The icon of the resource type or owner.
          nullable: true
        info:
          type: string
          title: info
          description: |-
            The meta data of the resource link.
             It can be the title of the target resource.
          nullable: true
        label:
          type: string
          title: label
          description: The label use to identify the resource type.
          nullable: true
      title: ResourceLink
      additionalProperties: false
      description: 'TODO: Auto delete resource link not linked to any other resource.'
    store.v1.CreateSupplierRequest:
      type: object
      properties:
        supplier:
          title: supplier
          description: The supplier information to create.
          $ref: '#/components/schemas/store.v1.Supplier'
        logoRawImage:
          type: string
          title: logo_raw_image
          format: byte
          description: The raw image of the logo of the supplier.
          nullable: true
        externalLinks:
          type: array
          items:
            $ref: '#/components/schemas/link.v1.ResourceLink'
          title: external_links
          description: The links of the supplier.
      title: CreateSupplierRequest
      additionalProperties: false
    store.v1.CreateSupplierResponse:
      type: object
      properties:
        supplierId:
          type: string
          title: supplier_id
          minLength: 3
          description: The reference id to the supplier identifier.
      title: CreateSupplierResponse
      required:
        - supplierId
      additionalProperties: false
    store.v1.DeleteSupplierRequest:
      type: object
      properties:
        supplierId:
          type: string
          title: supplier_id
          minLength: 3
          description: The reference id to the supplier identifier.
      title: DeleteSupplierRequest
      required:
        - supplierId
      additionalProperties: false
    store.v1.DeleteSupplierResponse:
      type: object
      properties:
        success:
          type: boolean
          title: success
          description: Whether the supplier was successfully deleted.
      title: DeleteSupplierResponse
      additionalProperties: false
    store.v1.GetStoreSuppliersRequest:
      type: object
      properties:
        storeId:
          type: string
          title: store_id
          minLength: 3
          description: The reference id to the store identifier.
      title: GetStoreSuppliersRequest
      required:
        - storeId
      additionalProperties: false
    store.v1.GetStoreSuppliersResponse:
      type: object
      properties:
        suppliers:
          type: array
          items:
            $ref: '#/components/schemas/store.v1.Supplier'
          title: suppliers
          description: |-
            The list of suppliers of the store.
             Note: Only the ids and names of the suppliers are returned.
      title: GetStoreSuppliersResponse
      additionalProperties: false
    store.v1.GetSupplierRequest:
      type: object
      properties:
        supplierId:
          type: string
          title: supplier_id
          minLength: 3
          description: The reference id to the supplier identifier.
      title: GetSupplierRequest
      required:
        - supplierId
      additionalProperties: false
    store.v1.GetSupplierResponse:
      type: object
      properties:
        supplier:
          title: supplier
          description: The retrieved supplier data.
          $ref: '#/components/schemas/store.v1.Supplier'
      title: GetSupplierResponse
      additionalProperties: false
    store.v1.Link:
      type: object
      properties:
        label:
          type: string
          title: label
          description: The label of the link.
        url:
          type: string
          title: url
          description: |-
            The url of the link.
             Todo: We must automatically retrieve the icon of the link.
      title: Link
      additionalProperties: false
    store.v1.StreamStoreSuppliersRequest:
      type: object
      properties:
        storeId:
          type: string
          title: store_id
          minLength: 3
          description: The reference id to the store identifier.
      title: StreamStoreSuppliersRequest
      required:
        - storeId
      additionalProperties: false
    store.v1.StreamStoreSuppliersResponse:
      type: object
      properties:
        suppliers:
          type: array
          items:
            $ref: '#/components/schemas/store.v1.Supplier'
          title: suppliers
          description: |-
            The list of suppliers of the store.
             Note: Only the ids and names of the suppliers are returned.
      title: StreamStoreSuppliersResponse
      additionalProperties: false
    store.v1.Supplier:
      type: object
      properties:
        refId:
          type: string
          title: ref_id
          description: The reference id to the supplier identifier.
          nullable: true
        name:
          type: string
          title: name
          description: The name of the supplier.
        description:
          type: string
          title: description
          description: The description of the supplier.
          nullable: true
        logoLinkId:
          type: string
          title: logo_link_id
          description: The id of the media of the logo of the supplier.
          nullable: true
        externalLinksIds:
          type: array
          items:
            type: string
          title: external_links_ids
          description: The links of the supplier.
        contactPhone:
          type: string
          title: contact_phone
          description: The contact phone number.
          nullable: true
        contactEmail:
          type: string
          title: contact_email
          description: The contact email.
          nullable: true
        contactAddress:
          type: string
          title: contact_address
          description: The contact address.
          nullable: true
        isActive:
          type: boolean
          title: is_active
          description: Whether the supplier is active.
        storeIds:
          type: array
          items:
            type: string
          title: store_ids
          description: The ids of the store of the supplier.
      title: Supplier
      additionalProperties: false
    store.v1.UpdateSupplierRequest:
      type: object
      properties:
        supplier:
          title: supplier
          description: |-
            The supplier information to update.
             Note:Only the fields that are set will be updated.
          $ref: '#/components/schemas/store.v1.Supplier'
        logoRawImage:
          type: string
          title: logo_raw_image
          format: byte
          description: The raw image of the logo of the supplier.
          nullable: true
        externalLinks:
          type: array
          items:
            $ref: '#/components/schemas/link.v1.ResourceLink'
          title: external_links
          description: The links of the supplier.
      title: UpdateSupplierRequest
      additionalProperties: false
    store.v1.UpdateSupplierResponse:
      type: object
      properties:
        supplier:
          title: supplier
          description: The updated supplier data.
          $ref: '#/components/schemas/store.v1.Supplier'
      title: UpdateSupplierResponse
      additionalProperties: false
security: []
tags:
  - name: store.v1.SupplierService
