openapi: 3.1.0
info:
  title: identity.v1
paths: {}
components:
  schemas:
    identity.v1.StoreInvoicePermission:
      type: object
      properties:
        readInvoice:
          type: boolean
          title: read_invoice
        createInvoice:
          type: boolean
          title: create_invoice
      title: StoreInvoicePermission
      additionalProperties: false
      description: / ----- INVOICE ----- ///
    identity.v1.StoreMemberPermission:
      type: object
      properties:
        readInformation:
          type: boolean
          title: read_information
        inviteMember:
          type: boolean
          title: invite_member
        updateMember:
          type: boolean
          title: update_member
        deleteMember:
          type: boolean
          title: delete_member
      title: StoreMemberPermission
      additionalProperties: false
      description: / ----- MEMBER ----- ///
    identity.v1.StoreOrderPermission:
      type: object
      properties:
        readOrder:
          type: boolean
          title: read_order
        createOrder:
          type: boolean
          title: create_order
      title: StoreOrderPermission
      additionalProperties: false
      description: / ----- ORDER ----- ///
    identity.v1.StorePermissions:
      type: object
      properties:
        product:
          title: product
          $ref: '#/components/schemas/identity.v1.StoreProductPermission'
        member:
          title: member
          $ref: '#/components/schemas/identity.v1.StoreMemberPermission'
        report:
          title: report
          $ref: '#/components/schemas/identity.v1.StoreReportPermission'
        order:
          title: order
          $ref: '#/components/schemas/identity.v1.StoreOrderPermission'
        invoice:
          title: invoice
          $ref: '#/components/schemas/identity.v1.StoreInvoicePermission'
        supplier:
          title: supplier
          $ref: '#/components/schemas/identity.v1.StoreSupplierPermission'
        transaction:
          title: transaction
          $ref: '#/components/schemas/identity.v1.StoreTransactionPermission'
      title: StorePermissions
      additionalProperties: false
      description: / ----- STORE PERMISSIONS (AGGREGATOR) ----- ///
    identity.v1.StoreProductPermission:
      type: object
      properties:
        readProductInInventory:
          type: boolean
          title: read_product_in_inventory
        createProductInInventory:
          type: boolean
          title: create_product_in_inventory
        updateProductInInventory:
          type: boolean
          title: update_product_in_inventory
        deleteProductInInventory:
          type: boolean
          title: delete_product_in_inventory
      title: StoreProductPermission
      additionalProperties: false
      description: / ----- PRODUCT ----- ///
    identity.v1.StoreReportPermission:
      type: object
      properties:
        readReport:
          type: boolean
          title: read_report
      title: StoreReportPermission
      additionalProperties: false
      description: / ----- REPORT ----- ///
    identity.v1.StoreSupplierPermission:
      type: object
      properties:
        readSupplier:
          type: boolean
          title: read_supplier
        createSupplier:
          type: boolean
          title: create_supplier
        updateSupplier:
          type: boolean
          title: update_supplier
        deleteSupplier:
          type: boolean
          title: delete_supplier
      title: StoreSupplierPermission
      additionalProperties: false
      description: / ----- SUPPLIER ----- ///
    identity.v1.StoreTransactionPermission:
      type: object
      properties:
        readTransaction:
          type: boolean
          title: read_transaction
        createTransaction:
          type: boolean
          title: create_transaction
        updateTransaction:
          type: boolean
          title: update_transaction
      title: StoreTransactionPermission
      additionalProperties: false
      description: / ----- TRANSACTION ----- ///
security: []
tags:
  - name: identity.v1.PermissionService
