name: Pre-Submit (Scripts)
on:
  workflow_call:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/presubmit_scripts.yml'
              - 'scripts/**'

  shellcheck:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Install pre-requisites.
      - uses: actions/checkout@v4

      # Lint all our shell scripts.
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "scripts"
          pattern: "*.sh"

  shfmt:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shfmt@v1
